### ISSUE TITLE
HTTP response from 'getAccountBalance' is not consistent

### ISSUE THREAD

**Issue by fagossa** [maucasco/myFirtsSpringBootService#3]
The response from the endpoint 'getAccountBalance' is 200 OK even if the account does not exist. So as a service consumer it is not easy to determine when the call worked successfully or not.

It is a good practice to return specific HTTP errors to explain the result:

https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

For example:
- 200 OK, everything worked normally
- 400 Bad request, error in parameters
- 403 Forbidden, not enough priviliges

**Comment by maucasco** [comment]
add method notFound an throw  EmptyResultDataAccessException when account not exist

**Comment by fagossa** [comment]
Remember the way I managed exceptions in the base example. 

An extract could be found here:

https://gist.github.com/fagossa/95ab5f0edcdc26d7e946dfb4a85efbcb

You have the full version here:

https://github.com/fagossa/demo_springboot_reactjs/blob/master/src/main/java/com/lucasian/payroll/employee/EmployeeSearchController.java

**Comment by fagossa** [comment]
The additional tests added in [a new PR](https://github.com/maucasco/myFirtsSpringBootService/pull/6) will help to solve this problem
